services:
  app:
    build: .
    container_name: application
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATASOURCE_URL}
    depends_on:
      - database
    volumes:
      - .:/app
      - /app/node_modules
  database:
    image: postgres:16
    container_name: database
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATASOURCE_USER}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${DATASOURCE_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - compass_data:/var/lib/postgresql/data

volumes:
  compass_data:
